version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bright#1270
      - POSTGRES_DB=dockert
    ports:
      - "5432:5432"
    restart: on-failure
  backend:
    image: backend
    depends_on:
      - db
    build: #./backend
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:Bright#1270@db/dockert
    volumes:
      - ./backend:/code/app:ro
    ports:
      - "8081:8081"
    restart: on-failure
    #command: uvicorn app/src:app --host 0.0.0.0 --port 8081 --reload

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
volumes:
      postgres_data: